# Part 2

In [45]:
import numpy as np

Euclidean distance:

In [46]:
A = np.array([[1.0,2.0], [2.0,3.0], [4.0,5.0]])
p = np.array([3.0,2.0])
np.linalg.norm(A-p, axis=1)

array([2.        , 1.41421356, 3.16227766])

Manhattan distance:

In [47]:
np.abs(A - p).sum(axis=1)

array([2., 2., 4.])

Reference: https://stackoverflow.com/questions/47736531/vectorized-matrix-manhattan-distance-in-numpy

__Check that results match example.__

First with only 4 rows.

In [52]:
!sed -n 4873p income.train.txt.5k
!sed -n 4788p income.train.txt.5k
!sed -n 2592p income.train.txt.5k
!head -1 income.dev.txt

33, Federal-gov, Bachelors, Married-civ-spouse, Adm-clerical, White, Male, 42, United-States, >50K
47, Federal-gov, Bachelors, Married-civ-spouse, Adm-clerical, White, Male, 45, Germany, >50K
48, Federal-gov, Bachelors, Married-civ-spouse, Prof-specialty, White, Male, 44, United-States, >50K
45, Federal-gov, Bachelors, Married-civ-spouse, Adm-clerical, White, Male, 45, United-States, <=50K


In [56]:
import os


In [68]:
x=os.popen('head -1 income.dev.txt')
result = x.read()

In [41]:
train_lines = open("income.train.txt.5k").readlines()
train_lines = [line.strip().split(", ") for line in train_lines]
dev_lines = open("income.dev.txt").readlines()
dev_lines = [line.strip().split(", ") for line in dev_lines]

scope_lines = dev_lines[0:1] + train_lines[4872:4873] + train_lines[4787:4788] + train_lines[2591:2592]

train_data = [[value for idx, value in enumerate(line) if idx not in [0,7,9]] for line in scope_lines] # index 0, 7 are not categorical fields, 9 is target

mapping = {}
new_data = []

for row in train_data:
    new_row = []
    for j, x in enumerate(row):
        feature = (j, x)
        if feature not in mapping:
            mapping[feature] = len(mapping) # insert a new feature into the index
        new_row.append(mapping[feature])
    new_data.append(new_row)
    
num_data = 4
num_features = 90

binary_data = np.zeros((num_data, num_features + 2))
# store normalized numerical values
for idx, row in enumerate(new_data):
  for jdx in row:
    binary_data[idx][jdx] = 1
  binary_data[idx][num_features] = int(scope_lines[idx][0]) / 50
  binary_data[idx][num_features + 1] = int(scope_lines[idx][7]) / 50
    
scope_bin = binary_data

In [48]:
A = scope_bin[1:4]
p = scope_bin[0]
print(A)
print(p)

[[1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 0. 1. 1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0

In [43]:
man_dist = np.abs(A - p).sum(axis=1)
man_dist

array([0., 2., 2.])

In [44]:
eucl_dist = np.linalg.norm(A-p, axis=1)
eucl_dist

array([0.        , 1.41421356, 1.41421356])

__Repeat with the entire set.__

In [8]:
train_lines = open("income.train.txt.5k").readlines()
train_lines = [line.strip().split(", ") for line in train_lines]
dev_lines = open("income.dev.txt").readlines()
dev_lines = [line.strip().split(", ") for line in dev_lines]

scope_lines = dev_lines[0:1] + train_lines[0:5000]

train_data = [[value for idx, value in enumerate(line) if idx not in [0,7,9]] for line in scope_lines] # index 0, 7 are not categorical fields, 9 is target

mapping = {}
new_data = []

for row in train_data:
    new_row = []
    for j, x in enumerate(row):
        feature = (j, x)
        if feature not in mapping:
            mapping[feature] = len(mapping) # insert a new feature into the index
        new_row.append(mapping[feature])
    new_data.append(new_row)
    
num_data = 5001
num_features = 90

binary_data = np.zeros((num_data, num_features + 2))
# store normalized numerical values
for idx, row in enumerate(new_data):
  for jdx in row:
    binary_data[idx][jdx] = 1
  binary_data[idx][num_features] = int(scope_lines[idx][0]) / 50
  binary_data[idx][num_features + 1] = int(scope_lines[idx][7]) / 50
    
scope_bin = binary_data
scope_bin

array([[1., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [9]:
A = scope_bin[1:5000]
p = scope_bin[0]

In [10]:
man_dist = np.abs(A[:,None] - p).sum(-1)
man_dist = [val for sublist in man_dist for val in sublist]
man_dist = np.array(man_dist)

In [11]:
index = np.argpartition(man_dist, 3)[0:3]
index

array([1041,  295, 4872])

In [12]:
man_dist[index]

array([2., 2., 0.])

In [13]:
eucl_dist = np.linalg.norm(A-p, axis=1)

In [14]:
index = np.argpartition(eucl_dist, 3)[0:3]
index

array([1041,  295, 4872])

In [15]:
eucl_dist[index]

array([1.41421356, 1.41421356, 0.        ])

References:
https://www.quora.com/How-can-I-drop-brackets-in-a-Python-list-in-order-to-go-from-1-2-3-to-1-2-3?share=1
https://stackoverflow.com/questions/34226400/find-the-index-of-the-k-smallest-values-of-a-numpy-array

## Question 1

In [16]:
train_lines = open("income.train.txt.5k").readlines()
train_lines = [line.strip().split(", ") for line in train_lines]
dev_lines = open("income.dev.txt").readlines()
dev_lines = [line.strip().split(", ") for line in dev_lines]

scope_lines = dev_lines[999:1000] + train_lines[0:5000]

train_data = [[value for idx, value in enumerate(line) if idx not in [0,7,9]] for line in scope_lines] # index 0, 7 are not categorical fields, 9 is target

mapping = {}
new_data = []

for row in train_data:
    new_row = []
    for j, x in enumerate(row):
        feature = (j, x)
        if feature not in mapping:
            mapping[feature] = len(mapping) # insert a new feature into the index
        new_row.append(mapping[feature])
    new_data.append(new_row)
    
num_data = 5001
num_features = 90

binary_data = np.zeros((num_data, num_features + 2))
# store normalized numerical values
for idx, row in enumerate(new_data):
  for jdx in row:
    binary_data[idx][jdx] = 1
  binary_data[idx][num_features] = int(scope_lines[idx][0]) / 50
  binary_data[idx][num_features + 1] = int(scope_lines[idx][7]) / 50
    
scope_bin = binary_data
scope_bin

array([[1., 1., 1., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [1., 1., 0., ..., 0., 0., 0.],
       ...,
       [1., 1., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])

In [17]:
A = scope_bin[1:5000]
p = scope_bin[0]

In [18]:
eucl_dist = np.linalg.norm(A-p, axis=1)
eucl_dist

array([3.16227766, 2.64575131, 3.16227766, ..., 3.        , 1.41421356,
       3.        ])

In [19]:
index = np.argpartition(eucl_dist, 5)[0:6]
index

array([1010, 2450, 3769, 1713, 2003,  681])

In [20]:
eucl_dist[index]

array([0., 0., 0., 0., 0., 1.])

## Question 2

In [21]:
man_dist = np.abs(A[:,None] - p).sum(-1)
man_dist = [val for sublist in man_dist for val in sublist]
man_dist = np.array(man_dist)
man_dist

array([10.,  7., 10., ...,  9.,  2.,  9.])

In [22]:
index = np.argpartition(man_dist, 5)[0:6]
index

array([1010, 2450, 3769, 1713, 2003,  681])

In [23]:
man_dist[index]

array([0., 0., 0., 0., 0., 1.])

## Question 4

In [24]:
index = np.argpartition(eucl_dist, 9)[0:10]
index

array([1010, 2450, 3769, 1713, 2003,  681, 3680, 3698, 3526, 2922])

In [25]:
eucl_dist[index]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       1.        , 1.        , 1.        , 1.41421356, 1.41421356])

In [26]:
man_dist = np.abs(A[:,None] - p).sum(-1)
man_dist = [val for sublist in man_dist for val in sublist]
man_dist = np.array(man_dist)
man_dist

array([10.,  7., 10., ...,  9.,  2.,  9.])

In [27]:
index = np.argpartition(man_dist, 9)[0:10]
index

array([1010, 2450, 3769, 1713, 2003,  681, 3680, 3698, 3526, 2922])

In [28]:
man_dist[index]

array([0., 0., 0., 0., 0., 1., 1., 1., 2., 2.])